[ SMS_Report (TRUE),
  SMS_Group_Name ("BloodHound Data"),
  SMS_Class_ID ("SpecterOps|BloodHound Data|1.0"),
  Namespace ("root\\\\ccm") ]
class SMS_BloodHoundData : SMS_Class_Template
{
    [ SMS_Report (TRUE), key ]
    DateTime     CollectionDatetime;
    [ SMS_Report (TRUE) ]
    String     Output;
};